+incdir+../../hw/include
+incdir+../../hw/common/rtl
+incdir+../../hw/common/rtl/cdc
+incdir+../../hw/common/rtl/interface
+incdir+../../hw/common/rtl/tech
+incdir+../../hw/ip/archinfo/rtl
+incdir+../../hw/ip/rcu/rtl
+incdir+../../hw/ip/uart16550/rtl
+incdir+../../hw/ip/uart/rtl
+incdir+../../hw/ip/spi/legacy_apb/rtl
+incdir+../../hw/ip/spi/rtl
+incdir+../../hw/ip/gpio/rtl
+incdir+../../hw/ip/i2c/rtl
+incdir+../../hw/ip/timer/rtl
+incdir+../../hw/ip/clint/rtl
+incdir+../../hw/ip/plic/rtl
+incdir+../../hw/ip/rtc/rtl
+incdir+../../hw/ip/wdg/rtl
+incdir+../../hw/ip/pwm/rtl
+incdir+../../hw/ip/rng/rtl
+incdir+../../hw/ip/crc/rtl
+define+__VERILOG__
+define+USE_REAL_ARCHINFO
+define+USE_REAL_RCU
+define+USE_REAL_GPIO
+define+USE_REAL_I2C
+define+USE_REAL_TIMER
+define+USE_REAL_CLINT
+define+USE_REAL_PLIC
+define+USE_REAL_RTC
+define+USE_REAL_WDG
+define+USE_REAL_PWM
+define+USE_REAL_RNG
+define+USE_REAL_CRC
+define+USE_REAL_SPI
+define+USE_REAL_UART
../../hw/include/soc_pkg.sv
../../hw/common/rtl/config.svh
../../hw/common/rtl/utils/xchecker.sv
../../hw/common/rtl/cdc/cdc_sync.sv
../../hw/common/rtl/cdc/cdc_2phase.sv
../../hw/common/rtl/clkrst/clk_int_div.sv
../../hw/common/rtl/clkrst/rst_sync.sv
../../hw/common/rtl/clkrst/counter.sv
../../hw/common/rtl/tech/stdcell.sv
../../hw/common/rtl/utils/fifo.sv
../../hw/common/rtl/utils/register.sv
../../hw/common/rtl/utils/edge_det.sv
../../hw/common/rtl/utils/lfsr.sv
../../hw/ip/core/NPC-bstage.sv
../../hw/ip/core/ysyx_26010010.v
../../hw/soc/top/asic_top.v
../../hw/soc/top/tc_io.v
../../hw/soc/top/apb_delayer.sv
../../hw/soc/top/apb4_flat_stubs.sv
../../hw/ip/archinfo/rtl/apb4_archinfo.sv
../../hw/ip/rcu/rtl/rcu_core.sv
../../hw/ip/rcu/rtl/apb4_rcu.sv
../../hw/ip/clint/rtl/apb4_clint.sv
../../hw/ip/plic/rtl/plic_gateway.sv
../../hw/ip/plic/rtl/prio_tree.sv
../../hw/ip/plic/rtl/plic_core.sv
../../hw/ip/plic/rtl/apb4_plic.sv
../../hw/ip/rtc/rtl/apb4_rtc.sv
../../hw/ip/wdg/rtl/apb4_wdg.sv
../../hw/ip/pwm/rtl/apb4_pwm.sv
../../hw/ip/gpio/rtl/apb4_gpio.sv
../../hw/ip/i2c/rtl/i2c_master_bit_ctrl.sv
../../hw/ip/i2c/rtl/i2c_master_byte_ctrl.sv
../../hw/ip/i2c/rtl/apb4_i2c.sv
../../hw/ip/timer/rtl/apb4_tmr.sv
../../hw/ip/spi/legacy_apb/rtl/spi_clgen.v
../../hw/ip/spi/legacy_apb/rtl/spi_shift.v
../../hw/ip/spi/legacy_apb/rtl/spi_top.v
../../hw/ip/spi/legacy_apb/rtl/spi_top_apb.v
../../hw/ip/spi/rtl/spi_fifo.sv
../../hw/ip/spi/rtl/spi_clkgen.sv
../../hw/ip/spi/rtl/spi_tx.sv
../../hw/ip/spi/rtl/spi_rx.sv
../../hw/ip/spi/rtl/spi_ctrl.sv
../../hw/ip/spi/rtl/spi_apb_if.sv
../../hw/ip/spi/rtl/spi_core.sv
../../hw/ip/spi/rtl/apb4_spi.sv
../../hw/ip/uart16550/rtl/raminfr.v
../../hw/ip/uart16550/rtl/uart_sync_flops.v
../../hw/ip/uart16550/rtl/uart_rfifo.v
../../hw/ip/uart16550/rtl/uart_tfifo.v
../../hw/ip/uart16550/rtl/uart_receiver.v
../../hw/ip/uart16550/rtl/uart_transmitter.v
../../hw/ip/uart16550/rtl/uart_regs.v
../../hw/ip/uart16550/rtl/uart_top_apb.v
../../hw/ip/uart/rtl/uart_tx.sv
../../hw/ip/uart/rtl/uart_rx.sv
../../hw/ip/uart/rtl/uart_irq.sv
../../hw/ip/uart/rtl/apb4_uart.sv
../../hw/ip/rng/rtl/apb4_rng.sv
../../hw/ip/crc/rtl/crc8_model.sv
../../hw/ip/crc/rtl/crc16_model.sv
../../hw/ip/crc/rtl/crc32_model.sv
../../hw/ip/crc/rtl/apb4_crc.sv
../../hw/ip/flash/model/flash.v
../../hw/ip/psram/model/esp_psram64h/ESP_PSRAM64H.sv
../../hw/ip/psram/model/esp_psram64h/psram_core.sv
../../hw/ip/psram/model/esp_psram64h/psram.sv
