#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:
    raise SystemExit("ERROR: PyYAML is required. Install it with: python3 -m pip install pyyaml") from exc


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def sv_hex(value: int, width: int) -> str:
    digits = max(1, (width + 3) // 4)
    text = f"{value:0{digits}X}"
    groups = []
    while text:
        groups.append(text[-4:])
        text = text[:-4]
    return f"{width}'h{'_'.join(reversed(groups))}"


def require_int(data: dict[str, Any], path: str) -> int:
    node: Any = data
    for key in path.split("."):
        if not isinstance(node, dict) or key not in node:
            raise SystemExit(f"ERROR: missing required key: {path}")
        node = node[key]
    if not isinstance(node, int):
        raise SystemExit(f"ERROR: {path} must be an integer")
    return node


def region_name(name: str) -> str:
    return name.upper().replace("-", "_")


def generate(memory: dict[str, Any], clock_hz: int) -> str:
    address_width = require_int(memory, "address_width")
    reset_pc = require_int(memory, "reset.pc")
    regions = memory.get("regions")
    interrupts = memory.get("interrupts", {})

    if not isinstance(regions, dict):
        raise SystemExit("ERROR: regions must be a mapping")
    if interrupts is not None and not isinstance(interrupts, dict):
        raise SystemExit("ERROR: interrupts must be a mapping")

    lines = [
        "// Generated by scripts/gen_soc_pkg.py from config/memory.yml.",
        "// Do not edit this file directly.",
        "package soc_pkg;",
        f"  localparam int unsigned SOC_CLOCK_HZ = {clock_hz};",
        f"  localparam logic [{address_width - 1}:0] SOC_RESET_PC = {sv_hex(reset_pc, address_width)};",
        "",
    ]

    for name, region in regions.items():
        if not isinstance(region, dict):
            raise SystemExit(f"ERROR: regions.{name} must be a mapping")
        if "base" not in region or "size" not in region:
            raise SystemExit(f"ERROR: regions.{name} must define base and size")
        base = region["base"]
        size = region["size"]
        if not isinstance(base, int) or not isinstance(size, int):
            raise SystemExit(f"ERROR: regions.{name}.base and size must be integers")

        macro = region_name(name)
        lines.append(f"  localparam logic [{address_width - 1}:0] SOC_{macro}_BASE = {sv_hex(base, address_width)};")
        lines.append(f"  localparam logic [{address_width - 1}:0] SOC_{macro}_SIZE = {sv_hex(size, address_width)};")
        if isinstance(region.get("irq"), int):
            lines.append(f"  localparam int unsigned SOC_{macro}_IRQ = {region['irq']};")
        lines.append("")

    if "flash" in regions:
        lines.append("  localparam logic [31:0] SOC_BOOTROM_BASE = SOC_FLASH_BASE;")
        lines.append("")

    for name, irq in interrupts.items():
        if not isinstance(irq, int):
            raise SystemExit(f"ERROR: interrupts.{name} must be an integer")
        macro = region_name(str(name))
        lines.append(f"  localparam int unsigned SOC_IRQ_{macro} = {irq};")

    if interrupts:
        lines.append("")

    lines.append("endpackage")
    return "\n".join(lines) + "\n"


def main() -> int:
    root = repo_root()
    parser = argparse.ArgumentParser(description="Generate hw/include/soc_pkg.sv from config/memory.yml")
    parser.add_argument("--memory", type=Path, default=root / "config" / "memory.yml", help="input memory map yml")
    parser.add_argument("--output", type=Path, default=root / "hw" / "include" / "soc_pkg.sv", help="output SystemVerilog package")
    parser.add_argument("--clock-hz", type=int, default=50_000_000, help="SOC_CLOCK_HZ value")
    args = parser.parse_args()

    with args.memory.open("r", encoding="utf-8") as file:
        memory = yaml.safe_load(file)
    if not isinstance(memory, dict):
        raise SystemExit(f"ERROR: {args.memory} must contain a YAML mapping")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(memory, args.clock_hz), encoding="utf-8")
    print(f"generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
